### PR TITLE
First pass at rails:app:update

### PR DESCRIPTION
**Pull request by farias-r7**
MS-1213

- [x] VERIFY specs pass

### CODE REVIEW

**Comment by farias-r7** [comment]
This passes locally for me, not sure what's up with travis at the moment.

**Comment by farias-r7** [comment]
Looks like rake gem had a version major bump a few days ago when they broke something. They released a patch version today, so now it's all green :-)

**Comment by dmaloney-r7** [comment]
@farias-r7 can you please also lock rake to ~> 10.5 please. rake 11.x breaks some things

**Comment by farias-r7** [comment]
@dmaloney-r7 locked

**Pull request merged**
